### ISSUE TITLE
Serialize node

### ISSUE THREAD

**Issue by stellarhoof** [smartprocure/contexture-client#113]
Right now if you want to serialize a node, you have to serialize the entire tree, lookup the path and then stringify that. It'd be nice if the node itself could be serialized.

**Comment by daedalus28** [comment]
#149 adds support for single node update triggers, so this seems more reasonable to do now

**Comment by stellarhoof** [comment]
I didn't mention what the use case was or why this was useful and now I don't even know if it's necessary :/

**Comment by daedalus28** [comment]
I followed the rabbit hole and it appears to be used when serializing part of a tree - specifically how in our app, we generally only persist the `criteria` node and its children instead of the entire tree.

`serializeTreePath` is the method name in spark (which only helps team members with access to that repo, sorry)

**Comment by daedalus28** [comment]
This was added in https://github.com/smartprocure/contexture-client/commit/7760552e579e0f46ef9bc3624ba6582c5c492b2d

Sample usage:
```js
search.serialize(['root', 'report'])
```
