### ISSUE TITLE
Make errors explicit

### ISSUE THREAD

**Issue by sadasant** [smartprocure/contexture-client#24]
Currently, if there's any inconsistency on how we expect data inside the search objects or coming from the server, the library just breaks. We need a layer of resilience to prevent breaking on non-critical inconsistencies (as in, logging possible errors) and also a way to throw properly understandable errors.

This will fix the issue that we tried to address in this PR: https://github.com/smartprocure/contexture-client/pull/23

**Comment by daedalus28** [comment]
The challenge here is being careful not to mask other issues. For example, if a service isn't set it up right and not wrapped in `data`, #23 would have caused it to silently fail in a case like this if we simply passed service instead of wrapping in `data`:

https://github.com/smartprocure/contexture-imdb/blob/master/src/components/MovieResults.js#L61-L63

On option is something like this (suggested by @sadasant):
```js
if (!F.cascade(['data', 'error'], response))
  throw 'The service needs to answer with an object with data or error'
```

However, it really highlights the need for a larger discussion around errors in general. Errors in the tree are local per node, and the top level error is a catch-all for things hitting the fan. An alternative might be to remove data/error props and maybe rely on status codes or something similar to have the body be the actual error and not wrap in `data`.

**Comment by daedalus28** [comment]
Errors are now returned as part of the tree (including requests and responses for use in the contexture dev tools), so the only place this would add value would be using the client without contexture powering the backend (which isn't supported).
